In [1]:
pip install quandl

In [0]:
import quandl
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [3]:
df = quandl.get("WIKI/MSFT")
print(df.head())

             Open   High   Low  ...  Adj. Low  Adj. Close   Adj. Volume
Date                            ...                                    
1986-03-13  25.50  29.25  25.5  ...  0.058941    0.064720  1.031789e+09
1986-03-14  28.00  29.50  28.0  ...  0.064720    0.067031  3.081600e+08
1986-03-17  29.00  29.75  29.0  ...  0.067031    0.068187  1.331712e+08
1986-03-18  29.50  29.75  28.5  ...  0.065876    0.066454  6.776640e+07
1986-03-19  28.75  29.00  28.0  ...  0.064720    0.065298  4.789440e+07

[5 rows x 12 columns]


In [13]:
df = df[["Adj. Close"]]
df

Adj. Close
Date                  
1986-03-13    0.064720
1986-03-14    0.067031
1986-03-17    0.068187
1986-03-18    0.066454
1986-03-19    0.065298
...                ...
2018-03-21   92.480000
2018-03-22   89.790000
2018-03-23   87.180000
2018-03-26   93.780000
2018-03-27   89.470000

[8076 rows x 1 columns]

In [0]:
forecast_out = 3
df['Prediction'] = df[['Adj. Close']].shift(-forecast_out)

In [15]:
df.head()

Adj. Close  Prediction
Date                              
1986-03-13    0.064720    0.066454
1986-03-14    0.067031    0.065298
1986-03-17    0.068187    0.063564
1986-03-18    0.066454    0.061831
1986-03-19    0.065298    0.060097

In [7]:
df.tail()

Adj. Close  Prediction
Date                              
2018-03-21       92.48         NaN
2018-03-22       89.79         NaN
2018-03-23       87.18         NaN
2018-03-26       93.78         NaN
2018-03-27       89.47         NaN

In [0]:
X = np.array(df.drop(['Prediction'],1))
X = X[:-forecast_out]

In [0]:
Y = np.array(df['Prediction'])
Y = Y[:-forecast_out]

In [0]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

In [19]:
#SVM (SVR)
SVR_rbf = SVR(kernel='rbf', C = 1e3, gamma=0.1)
SVR_rbf.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [20]:
#test
confidence_svm = SVR_rbf.score(x_test, y_test)
print(confidence_svm)

0.9985282278334937


In [21]:
lr = LinearRegression()
lr.fit(x_train, y_train)
confidence_lr = lr.score(x_test, y_test)
print(confidence_lr)

0.9985367754762173


In [0]:
x_forecast = np.array(df.drop(['Prediction'], 1))[-forecast_out:]

In [23]:
x_forecast

array([[87.18],
       [93.78],
       [89.47]])

In [24]:
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

[87.3300236  93.94113377 89.62387849]


In [26]:
svm_prediction = SVR_rbf.predict(x_forecast)
print(svm_prediction)

[88.1992058  93.73299491 91.14729969]
